# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Pending status
        uses: ouzi-dev/commit-status-updater@v1.1.2
        with:
          status: "pending"
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Check codestyle
        run: mvn checkstyle:check
#      - name: Check for PMD violations
#        run: mvn pmd:check
#      - name: Check for CPD violations
#        run: mvn pmd:cpd-check
      - name: Build with Maven
        run: mvn --batch-mode verify
#      - name: Run SpotBugs static analysis
#        run: mvn spotbugs:check
      - name: Check coverage and mutation
        run: mvn pitest:mutationCoverage
      - name: Status check
        if: always()
        uses: ouzi-dev/commit-status-updater@v1.1.2
        with:
          addHoldComment: "true"
          status: "${{ job.status }}"
